# Generated by Django 3.1.7 on 2021-03-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.reviewtarget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewtarget',
            name='type',
            field=models.CharField(choices=[('tch', 'Преподаватель'), ('sbj', 'Предмет')], max_length=3),
        ),
    ]
