# Generated by Django 3.1.7 on 2021-03-25 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210325_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 23, 53, 22, 905452)),
        ),
    ]
